apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: update-frontend
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: gitops-repo
  interval: 1m
  update:
    path: ./applications/frontend
    strategy: Setters
